"""Contract tests for dependency and compatibility configuration."""

from __future__ import annotations

from pathlib import Path
from typing import cast

import yaml

PROJECT_ROOT = Path(__file__).resolve().parents[2]


def _load_mapping(path: Path) -> dict[str, object]:
    loaded: object = yaml.safe_load(path.read_text(encoding="utf-8"))
    assert isinstance(loaded, dict)
    return cast(dict[str, object], loaded)


def _as_mapping(value: object) -> dict[str, object]:
    assert isinstance(value, dict)
    return cast(dict[str, object], value)


def test_python_and_ml_versions_match_compatibility_contract() -> None:
    compatibility = _load_mapping(PROJECT_ROOT / "configs" / "compatibility.yaml")
    python = _as_mapping(compatibility["python"])
    pytorch = _as_mapping(compatibility["pytorch"])
    onnxruntime = _as_mapping(compatibility["onnxruntime"])

    assert (PROJECT_ROOT / ".python-version").read_text(encoding="utf-8").strip() == "3.11.15"
    assert python["version"] == "3.11.15"
    assert pytorch["torch_version"] == "2.13.0"
    assert pytorch["torchvision_version"] == "0.28.0"
    assert onnxruntime["cpu_version"] == "1.27.0"


def test_requirement_exports_are_lock_generated_and_environment_specific() -> None:
    colab = (PROJECT_ROOT / "requirements" / "colab.txt").read_text(encoding="utf-8")
    serving = (PROJECT_ROOT / "requirements" / "serving.txt").read_text(encoding="utf-8")

    assert "autogenerated by uv" in colab
    assert "torch==2.13.0" in colab
    assert "torchvision==0.28.0" in colab
    assert "open-clip-torch==3.3.0" in colab
    assert "--hash=sha256:" in colab

    assert "autogenerated by uv" in serving
    assert "fastapi==0.139.2" in serving
    assert "onnxruntime==1.27.0" in serving
    assert "torch==2.13.0" not in serving
    assert "--hash=sha256:" in serving


def test_lock_and_precommit_configuration_exist() -> None:
    assert (PROJECT_ROOT / "uv.lock").is_file()

    precommit = _load_mapping(PROJECT_ROOT / ".pre-commit-config.yaml")
    assert precommit["minimum_pre_commit_version"] == "4.6.0"
    assert isinstance(precommit["repos"], list)


def test_compose_and_environment_example_define_logging_contract() -> None:
    compose = _load_mapping(PROJECT_ROOT / "compose.yaml")
    logging_environment = _as_mapping(compose["x-logging-environment"])

    assert logging_environment == {
        "LOG_LEVEL": "${LOG_LEVEL:-INFO}",
        "LOG_FORMAT": "json",
        "SERVICE_NAME": "${SERVICE_NAME:-ml-challenge}",
        "APP_ENV": "${APP_ENV:-podman}",
        "GIT_SHA": "${GIT_SHA:-unknown}",
    }
    assert compose["services"] == {}

    env_example = (PROJECT_ROOT / ".env.example").read_text(encoding="utf-8")
    for entry in (
        "APP_ENV=development",
        "GIT_SHA=unknown",
        "LOG_LEVEL=INFO",
        "LOG_FORMAT=console",
        "SERVICE_NAME=ml-challenge",
        "POSTGRES_HOST=postgres",
        "POSTGRES_PORT=5432",
        "POSTGRES_DB=ml_platform",
        "POSTGRES_USER=ml_user",
        "POSTGRES_PASSWORD=change-me",
        "REDIS_HOST=redis",
        "REDIS_PORT=6379",
        "MLFLOW_TRACKING_URI=http://mlflow:5000",
    ):
        assert entry in env_example

    gitignore = (PROJECT_ROOT / ".gitignore").read_text(encoding="utf-8")
    assert ".env" in gitignore.splitlines()
    assert "!.env.example" in gitignore.splitlines()
